apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
    zone: "${ZONE}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
      zone: "${ZONE}"
  template:
    metadata:
      labels:
        app: mosquitto
        zone: "${ZONE}"
    spec:
      nodeSelector:
        zone: "${ZONE}"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1883
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2
          ports:
            - containerPort: 1883
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
    zone: "${ZONE}"
spec:
  type: NodePort
  externalTrafficPolicy: Local  # makes the node only serve traffic to pods running on itself
  selector:
    app: mosquitto
    zone: "${ZONE}"
  ports:
    - port: 1883
      targetPort: 1883
      nodePort: ${NODE_PORT}
