apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      nodeSelector:
        node-role: fog
      securityContext:
        runAsNonRoot: true
        runAsUser: 1883
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2
          ports:
            - containerPort: 1883
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: default
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    persistence false
    log_dest stdout
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: default
spec:
  type: NodePort
  selector:
    app: mosquitto
  ports:
    - port: 1883
      targetPort: 1883
      nodePort: 30183
